### ISSUE TITLE
DevConf.us 2020 virtual event CfP asks for Booths and Meetups

### ISSUE THREAD

**Issue by tyll** [devconfcz/devconf#103]
The CfP https://cfp.devconf.info/submit/15 asks for Booths and Meetups, will there be some kind of virtual Booths and Meetups or is this a leftover from the physical idea? Please clarify this.

**Comment by whitel** [comment]
yes, we plan to do "something" for booths and meetups.. not quite sure how.. but the booths are likely a chat room all day and the meetups chatrooms for their scheduled slot. Sorry about the lag on this, I didn't realize it was a question.

**Comment by tyll** [comment]
So what's the result? It would be great to get some information about what will be possible or clarification that nothing is possible instead of getting the ticket closed without a comment.

**Comment by jridky** [comment]
@langdon I assume, you have some idea, how this will be handled at DevConf.US 2020. Can you share some insights?

**Comment by langdon** [comment]
Sorry, we are still waiting for platform confirmation which will inform this decision.

**Comment by jridky** [comment]
Ok, let's wait for the final decision.

**Comment by jridky** [comment]
Closing due DevConf.US 2020 is over now.
