### ISSUE TITLE
Telegram a/c doesn't exists

### ISSUE THREAD

**Issue by deepak1725** [devconfcz/devconf#128]
There is No Telegram A/c with handle @devconfus exists

https://github.com/devconfcz/devconf/blob/49bd9a9f86d6a5c99f67a7690462d911786cbc40/source/us/index.blade.php#L59

https://github.com/devconfcz/devconf/blob/49bd9a9f86d6a5c99f67a7690462d911786cbc40/build_production/us/index.html#L83

**Comment by langdon** [comment]
Fixed this by changing the group name to be consistent with the others. No code change required.
