### ISSUE TITLE
DevConf.CZ 2022 is not listed on sched.com

### ISSUE THREAD

**Issue by Jakob-Naucke** [devconfcz/devconf#148]
The proposal confirmation form has a field:
> **Your sched.org email**
> We need this email to be able to give you access to your talk at sched.org

I tried creating an account on https://sched.org (forwards to https://sched.com), whose [login page](https://sched.com/login) will tell you you can register based on the event you're signing up for ([list](https://sched.com/directory)). DevConf.CZ 2022 does not appear to be in this list (yet?), therefore, I cannot create an account.

**Comment by jridky** [comment]
Finally, its available at https://devconfcz2022.sched.com/
