### ISSUE TITLE
"My confirmed events" not sorted

### ISSUE THREAD

**Issue by mureinik** [devconfcz/devconf#150]
Steps to reproduce:

1. Log in to https://cfp.devconf.info/
2. Go to "My Accepted"
3. If you have accepted proposals in several events, "My confirmed events" at the bottom of the screen is not sorted. See screenshot:

![devconf_sorting](https://user-images.githubusercontent.com/4173849/149325642-258a04ce-9e3f-4544-8fd6-162f2d9c3ca7.png)

Requested behavior:
Either sort the accepted conferences by ascending date (for this example: DevConf.cz 2020, DevConf.us 2020, DevConf.cz 2021, DevConf.cz 2022) or alphanumerically (for this example: DevConf.cz 2020, DevConf.cz 2021, DevConf.cz 2022, DevConf.us 2020)

**Comment by jridky** [comment]
solved
