### ISSUE TITLE
US site not updated

### ISSUE THREAD

**Issue by sallyom** [devconfcz/devconf#165]
@jridky this might be bc I'm not very useful with front-end stuff, but the US site isn't looking like it does in my development env, see the screenshots below - did I forget to build something in the recent PR?

**Comment by sallyom** [comment]
![Screenshot from 2022-06-18 17-35-17](https://user-images.githubusercontent.com/11166065/174457724-5d7048cd-3cd8-43c7-88c0-1774eee1736f.png)
![Screenshot from 2022-06-18 17-35-25](https://user-images.githubusercontent.com/11166065/174457725-df41ee75-7a1c-4548-a230-acf8ac41bec0.png)
![Screenshot from 2022-06-18 17-35-32](https://user-images.githubusercontent.com/11166065/174457728-83d76d89-d438-40b6-93ca-76a975ccedd4.png)

**Comment by jridky** [comment]
just try it now, or use shift+r to force reload

**Comment by sallyom** [comment]
Oh! Thanks so much!! You're the best :)

**Comment by sallyom** [comment]
You also fixed the dates - I tried!
