### ISSUE TITLE
No travel information sections

### ISSUE THREAD

**Issue by bonzini** [devconfcz/devconf#186]
The devconf.us website has "Getting around Boston" and "Getting to Boston" sections.

This is a very important section to have for devconf.cz as well; attendees may not be familiar with advantages and disadvantages of reaching Brno from Prague/Vienna/Bratislava, how to book buses, taxi prices in case they want to share one, etc. Some basic information on DPMB would also be nice to have.

**Comment by dvolavko** [comment]
Getting to Brno has been updated, closing.
