### ISSUE TITLE
DevConf.CZ '19 - Add Brno travel section

### ISSUE THREAD

**Issue by kejbaly2** [devconfcz/devconf#31]
Create a travel section for the 2019 event page. Merge info from 2018 event page (https://github.com/devconfcz/devconf/blob/master/templates/www/cz/2018/devconfcz-2018-travel.html) and https://cz.pycon.org/2016/about/brno/index.html

**Comment by bexelbie** [comment]
closing as we can use the one we pulled from 18 into 19 :)
