### ISSUE TITLE
DevConf.CZ '20 - Stub site - Add FAQ section

### ISSUE THREAD

**Issue by kejbaly2** [devconfcz/devconf#32]
Add FAQ section to '19 event page

Example could be copied from '18 event

https://github.com/devconfcz/devconf/blob/master/templates/www/cz/2018/devconfcz-2018-faq.html

Initially content can be exactly the same, just updated for '19 in case there are dates or references to '18.

**Comment by bexelbie** [comment]
closing as we can use 19's faq for 20
