### ISSUE TITLE
broken media-policy redirect

### ISSUE THREAD

**Issue by whitel** [devconfcz/devconf#76]
If you try to go to https://devconf.info/media-policy.html, you get a 404. However, if you go to https://www.devconf.info/media-policy.html it works. https://devconf.info/media-policy.html appears to redirect to https://devconf.info/coc which is where the actual fail is.

**Comment by whitel** [comment]
We need https://devconf.info/media-policy to work or we also need to update the eventbrite reg page

**Comment by jridky** [comment]
Fixed by proper .htaccess content
