### ISSUE TITLE
Getting around Brno: BrnoID

### ISSUE THREAD

**Issue by webknjaz** [devconfcz/devconf#88]
Hi,

I think it'd be useful to add https://www.brnoid.cz/en/eoc to the page https://github.com/devconfcz/devconf/blob/a1eaa50/source/cz/aroundbrno.blade.php. I'm surprised that it's not already there.

It allows one to (1) buy a ticket for the specified number of days, (2) bind such ticket to any contactless bank card, (3) upfront, (4) international (unlike SMS tickets which can only be bought via SMS using CZ/SK phone numbers). (5) This method allows to avoid communicating with non-English-speaking ppl. (6) And if a group of people comes, it all can be set up from within one account with subaccounts.

**Comment by bexelbie** [comment]
I wasn't aware that it was possible to buy tickets online and bind them to a contactless card without visiting a verification location.  This need is mentioned in the first FAQ.  Can you link to the specific page that is for visitors?

**Comment by webknjaz** [comment]
> without visiting a verification location

1) when one registers, they get a "Basic" account, but if they do the identity verification, they get a "Full" badge at the top.
2) verification deadline is 30 days, if you buy a non-transferable ticket
3) visitors should buy transferable tickets that are slightly more expensive (actually vice versa — it's non-transferable ones that are cheaper) but AFAIU this doesn't require any sort of verification as these tickets are roughly equivalent to standard paper bills that you can get from the yellow machines.

**Comment by webknjaz** [comment]
> bind them to a contactless card without visiting a verification location

Verification is NOT for binding to contactless, this is done offline. it's for checking that what you entered in your profile (name, address, photo) matches your ID.

**Comment by webknjaz** [comment]
Read the first two FAQ items here: https://www.brnoid.cz/en/eoc#cms.

<details>
<summary>
  <strong>[NON-TRANSFERABLE, NEEDS VERIFICATION DURING 21 DAYS]</strong>
  What do I need to buy a non-transferable public transport ticket?
</summary>

> In order to buy a non-transferable public transport ticket you need to create a registration on eshop of BrnoID.cz, then you have to fill in all your personal information in "My account" section where you also have to upload your photo. After you will successfully complete all previous steps a purchase of non-transferable transportation card will be enabled for you. In order to buy it, just click on "Buy a ticket" button on the left side of the eshop. First you need to add a ticket carrier by using button "Add a new ticket carrier" and then select him with "Select a carrier". Then you select a fare category and confirm it using "Select" button. If your needed category is not listed, you can click on "Resolve" button to add it temporarily. The third step is selecting a ticket itself – monthly, quarterly or one year ticket. When you’re done, confirm it with "Select" button. As the last step you have to select a date when the validity of the ticket should start. You can select any date including the day when you are buying it, up to 30 days in advance. This step is confirmed by using "Add to cart" button and then you have to confirm the whole selection with "Proceed to checkout" button. Now you can select the method of payment. You can select either the option of paying using GoPay that enables you to pay using internet banking of some banks, or you can pay via bank card online. If you don’t want to use this method, you can select the second one, but only if your public transport ticket begins its validity in 5 or more working days. This method is called Pay via OFFLINE bank transfer. If you’ll select GoPay, your payment will only need to be confirmed – you don’t need to fill anything in it. As for the second method, you’ll obtain data needed to make the payment.
>
> After the first purchase of your public transport ticket, you also need to verify your information on any of the verification places using your ticket carrier and an ID card, that mentions all of the required data. You have up to 21 days to verify it and in case that you have used the "Resolve" button, you have 5 working days. The list of the verification places can be found either in tips section or on the bottom of the eshop in Verification places section.
</details>

<details>
<summary>
  <strong>[TRANSFERABLE, DOESN'T EVEN MENTION FILLING IN ACCOUNT DATA]</strong>
  What do I need to buy a transferable public transport ticket?
</summary>

> In order to buy a transferable public transport ticket you need to create a registration on eshop of BrnoID.cz (using just an e-mail adress and setting up your password). In order to buy it, just click on "Buy a ticket" button on the left side of the eshop. First you need to add a ticket carrier by using button "Add a new ticket carrier" and then select him with "Select a carrier". Next step is selecting a ticket itself and when you’re done, confirm it with "Select" button. As the last step you have to select a date and time when the validity of the ticket should start. You can select any date including the day when you are buying it, up to 30 days in advance. This step is confirmed using "Add to cart button" and then you have to confirm the whole selection with "Proceed to checkout" button. Now you can select the method of payment. You can select either the option of paying using GoPay that enables you to pay using internet banking of some banks, or you can pay via bank card online. If you don’t want to use this method, you can select the second one, but only if your transportation card begins its validity in 5 or more working days. This method is called Pay via OFFLINE bank transfer. If you’ll select GoPay, your payment will only need to be confirmed – you don’t need to fill anything in it. As for the second method, you’ll obtain data needed to make the payment.
>
> Attention: if you need to transfer this ticket to another carrier, this is limited by the number of immediate transfers (for short-term transfers to two, up to six for one-year portable salvia). Further transfers, after the immediate transfer limit is exceeded, are only possible with a 10-minute delay, after which the required transfer will need to be finally confirmed.
</details>

**Comment by webknjaz** [comment]
Oh, also AFAIU now those ticket verifiers in vehicles that are equipped with contactless terminals actually work since around July. (The ones that have been present in buses since at least two years ago and labeled "contactless payments don't work currently.")

AFAIR they work as follows:
1. You tap your card on entry (check-in). 25 Kč is locked on your card (as in a 60-minute ride).
2. If your ride was less than 15 min, you tap again on exit (check-out) and the amount charged would go down to 20 Kč (as in 15-min ticket).

(I haven't checked this in Brno but tried in Ostrava)

**Comment by jridky** [comment]
BrnoID project aims especially for Brno residents, that are using long term tickets for public transportation. Due of it I am not going to mention this service in Getting around Brno, because for DevConf purposes, long term public transport tickets are not suitable.

AFAIK, contact less terminals are available on single one bus line only (from Main train station to Brno Airport), and even for transferable tickets authorities need to verify data you've filled in the terminal.

**Comment by webknjaz** [comment]
> BrnoID project aims especially for Brno residents, that are using long term tickets for public transportation. Due of it I am not going to mention this service in Getting around Brno, because for DevConf purposes, long term public transport tickets are not suitable.

Actually, this is not completely true. One can choose to use **short-term** transferable tickets for 24 hours up to 30 days without any need to enter their personal data:
<img width="666" alt="brno-id-transferable-tickets" src="https://user-images.githubusercontent.com/578543/72160612-dfd06200-33be-11ea-8f8b-72851a94f3de.png">
They also emphasize this in the official video (https://youtu.be/RuFUDJWVIDY) on page https://www.brnoid.cz/en/cms/13-how-to.

Also, they even sell a tourist card (Brnopas: https://www.brnoid.cz/en/tic) which implies that the service is traveler-friendly.
